plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*

# Gemspec

Gemspec/DevelopmentDependencies:
  # Do not require adding developemnt dependencies to the Gemfile.
  Enabled: false

# Layout

Layout/LineLength:
  Max: 80
  Exclude:
    - "bin/*"

# Style

Style/AsciiComments:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  # Allow `include` in rake task root.
  Exclude:
    - "**/*.rake"

Style/StringLiterals:
  # Prefer "double quotes" over 'single quotes'.
  EnforcedStyle: double_quotes

# RSpec

RSpec/VerifiedDoubles:
  # Allow calling `double`.
  Enabled: false
