plugins:
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - spec/dummy/db/schema.rb

Gemspec/DevelopmentDependencies:
  # Do not require adding developemnt dependencies to the Gemfile.
  Enabled: false

RSpec/VerifiedDoubles:
  # Allow calling `double`.
  Enabled: false

Style/MixinUsage:
  # Allow `include` in rake task root.
  Exclude:
    - "**/*.rake"

Style/StringLiterals:
  # Prefer "double quotes" over 'single quotes'.
  EnforcedStyle: double_quotes
