name: Lint

on: [push]

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.316.0
        with:
          bundler-cache: true

      - name: RuboCop
        run: bin/rubocop
